---
version: '3'

services:
  proxy:
    image: "traefik:1.3.5"

    command: |
      --docker \
      --docker.swarmmode \
      --docker.domain=traefik \
      --docker.watch \
      --docker.exposedbydefault = false \
      --web

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "acme:/etc/traefik"

    networks:
      - gateway

    ports:
      - "80:80"
      - "8080:8080"

    deploy:
      restart_policy:
        condition: any
        window: 5s
        
      placement:
        constraints:
          - "node.role == manager"

volumes:
  acme: # TODO: rex-ray! https://rexray.readthedocs.io/en/stable/user-guide/docker-plugins/#digitalocean

networks:
  gateway:
    driver: overlay
