---
version: '3'

services:
  main:
    image: "brianhicks/elm-lang.org:0.18.0"

    networks:
      - gateway

    deploy:
      labels:
        traefik.docker.network: "proxy_gateway"
        traefik.enable: "true"
        traefik.frontend.rule: "Host:elm-lang.org"
        traefik.port: 8000

      replicas: 1

      update_config:
        delay: 30s

      restart_policy:
        condition: any
        window: 30s

  # redirect www to bare domain
  strip-www:
    image: "brianhicks/strip-www:1.0.0"

    networks:
      - gateway

    deploy:
      labels:
        traefik.docker.network: "proxy_gateway"
        traefik.enable: "true"
        traefik.frontend.rule: "Host:www.elm-lang.org"
        traefik.port: 80

      replicas: 1

networks:
  gateway:
    external:
      name: proxy_gateway
