---
version: '3'

services:
  package:
    image: "brianhicks/package.elm-lang.org:0.18.0"

    networks:
      - gateway

    volumes:
      - "packages:/etc/packages"

    deploy:
      labels:
        traefik.docker.network: "proxy_gateway"
        traefik.enable: "true"
        traefik.frontend.rule: "Host:package.elm-lang.org"
        traefik.port: 8000

      replicas: 1

      update_config:
        delay: 30s

      restart_policy:
        condition: any
        window: 30s

volumes:
  packages:
    external:
      name: packages

networks:
  gateway:
    external:
      name: proxy_gateway
