---
version: '3'

services:
  proxy:
    image: "traefik:1.3.7-alpine"

    command: |
      --acme \
      --acme.domains=letsdosome.science,www.letsdosome.science \
      --acme.domains=package.letsdosome.science \
      --acme.email=brian@brianthicks.com \
      --acme.storage=/mnt/certs/acme.json \
      --acme.entrypoint=https \
      --acme.acmeLogging=true \
      --acme.caServer="https://acme-staging.api.letsencrypt.org/directory" \
      --docker \
      --docker.swarmmode \
      --docker.domain=traefik \
      --docker.watch \
      --docker.exposedbydefault=false \
      --defaultEntryPoints=https,http \
      --entrypoints='Name:http Address::80' \
      --entrypoints='Name:https Address::443 TLS' \
      --logLevel=DEBUG \
      --web

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "certs:/mnt/certs"

    networks:
      - gateway

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    deploy:
      restart_policy:
        condition: any
        window: 5s
        
      placement:
        constraints:
          - "node.role == manager"

volumes:
  certs:
    external:
      name: certs

networks:
  gateway:
    driver: overlay
