---
version: '3'

services:
  proxy:
    image: "traefik:1.3.5-alpine"

    command: |
      --docker \
      --docker.swarmmode \
      --docker.domain=traefik \
      --docker.watch \
      --docker.exposedbydefault = false \
      --web

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "certs:/mnt/certs"

    networks:
      - gateway

    ports:
      - "80:80"
      - "8080:8080"

    deploy:
      restart_policy:
        condition: any
        window: 5s
        
      placement:
        constraints:
          - "node.role == manager"

volumes:
  certs:
    external:
      name: certs

networks:
  gateway:
    driver: overlay
