---
systemd:
  units:
    - name: elm-lang.org.service
      enable: true
      contents: |
        [Unit]
        Description=elm-lang.org
        After=docker.service
        Requires=docker.service
  
        [Service]
        ExecStartPre=-/usr/bin/docker stop %n
        ExecStartPre=-/usr/bin/docker rm %n
        ExecStartPre=/usr/bin/docker pull brianhicks/elm-lang.org:0.18.0
        ExecStart=/usr/bin/docker run --rm --name %n brianhicks/elm-lang.org:0.18.0
        ExecStop=/usr/bin/docker stop %n
  
        [Install]
        WantedBy=multi-user.target

passwd:
  users:
    - name: brian
      ssh_authorized_keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDS/ZRyWtv1am4JxArIi9fbDmnsOLNPoQ9+6NXV/3Go2EN7XFHKFYWDo830FMyvcQ835ASthKVfovdTaKHyc/M5GXsKmRzBKqWeiyq0kwz4vFFtUblFLGYUC9Ce4vvGzwKTF6IdBbH47WXZ2ncxdJsgZPoF89RQp+TzEr971CaVZa3sLzP94QfCkc2CM7I2zrX9Ocg/ZqjPQwQoyFDee8WjXxAcr7sWtxbmQvGmdRrlnPdwx8brJj6jUlttmiDhRi45ZKNvu7Qo14OwNbwZG49z9ark4+YHWdqb+niGruJjc787Mz3bQEx30+etjMUOR33urLPl6sn/z/pZAzsgvkva3Cb/6w/rb9g4OlSMovTtacx5NdEM/RmC1czq8Y3fyB9P6WkLyrouhsN0DXly9sh7iM2S9toknMTTzUzAXudZff5nGW9xNrpRjacHy6cVzJO/mCcJBTvicMjzeYArMqNnkHTAut4Nd9RbOWe+oqbiMg79fnOHOeDXkehg2eXwgqb8At6dqTs17wTsUsl035Eeiw35zr07D9oLV2AmZNzYwYUidQ1Foiu92BsHkQEvhjmr+1WR6CKOCsXSYEUqIojBax5oSZxrOlHHCIMX9ksCuy0jsoZIe1vKVcL2dPCWGZEPHLVz7T3kq4r8Hr1G29oLGzbaVYOLVl3JKgUZj4SBbQ== brian@flame.local"]
      create:
        groups:
          - sudo
          - wheel
          - docker
